### ISSUE TITLE
Importer creates duplicate assembly references

### ISSUE THREAD

**Issue by ElektroKill** [0xd4d/dnlib#406] opened 2020-10-24 12:31 UTC
Hello,
While using the importer I came across an issue.

I have a .net module which uses runtime version 2.0. I import the "BinaryWriter" type using `importer.ImportAsTypeSig(typeof(BinaryWriter))` for use in a local. I add a local of that TypeSig into the net2.0 module and write it. After inspecting the module's references in dnSpy I saw that a second reference to mscorlib was added. Now the module had one reference to mscorlib version 2.0 and another to version 4.0.

I expect the importer to use the already existing references.

Files that can be used to reproduce this behavior:
[DnlibIssue.zip](https://github.com/0xd4d/dnlib/files/5432868/DnlibIssue.zip)

NET20App.exe is the .net 2.0 module. DnlibImportIssue.exe opens that module does what explained above and writes it to a file named out.exe

Thanks in advance!

**Comment by CreateAndInject** [comment] 2020-10-25 10:06
Duplicate of #109, see also: #259

**Comment by 0xd4d** [comment] 2020-10-31 11:16
The Importer doesn't change any assembly references. You can pass in your `ImportMapper` and update the assembly references or you can use `MemberFinder` and update all assembly references it finds.

A `mscorlib v2.0` ref is not the same as `mscorlib v4.0` ref. They're not dupes.

**Comment by ElektroKill** [comment] 2020-11-01 17:13
Thanks for the response, could you please provide me with some example code on how to use the ImportMapper to remap the references to the already existing reference of a different version?

Thanks in advance

**Comment by 0xd4d** [comment] 2020-11-01 21:47
It's probably easier to use MemberRefFinder. Update all AssemblyRefs in all MemberRefs/TypeRefs/etc it finds

**Closed** 2020-11-04 23:25 UTC
