### ISSUE TITLE
Error in clearing/modifying Locals in method

### ISSUE THREAD

**Issue by CursedSheep** [0xd4d/dnlib#306] opened 2019-09-12 15:27 UTC
I have noticed that dnlib is not able to clear all locals or even modify it at mdtoken 0x0600010A.
Not sure if i am doing it correctly but what i did was i looped through every method and just used method.Body.Variables.Clear(); it seems that method 0x0600010A is not getting affected.

File: https://www22.zippyshare.com/v/CikOUSzP/file.html

**Comment by 0xd4d** [comment] 2019-09-13 16:44
Can you show a small repro?

**Comment by CursedSheep** [comment] 2019-09-14 01:13
Steps to reproduce:
1. Load file I uploaded in zippy share with dnlib function ModuledefMD.Load
2. Loop through every types and method and if method has body, clear all locals. Or just resolve token of the method "0x0600010A".
3. Save the file. 
4. Check saved file in dnspy and look for the method, and you'll see locals were unmodified. 

Other way to reproduce:
1. Load the file I uploaded on zippy share and use dnspy
2. Try modifying any locals or clearing the locals in the method "0x0600010A".
3. Save file. 
4. Check saved file in dnspy and look for the method, and you'll see locals were unmodified.

**Comment by 0xd4d** [comment] 2019-09-19 06:16
Can you attach the file here?

**Comment by CursedSheep** [comment] 2019-09-19 12:32
I already did.
**File**: https://www22.zippyshare.com/v/CikOUSzP/file.html

**Comment by 0xd4d** [comment] 2019-09-19 14:20
I mean attach the file here and not add a link to some download site with lots of popups.

**Comment by 0xd4d** [comment] 2019-09-20 19:03
This is probably related or same issue as https://github.com/0xd4d/dnlib/issues/299

**Comment by CursedSheep** [comment] 2019-09-23 09:59
Here's the link. also i tried not preserving RIDs and still not working.
https://mega.nz/#!GHoEHAbR!wisW2KmZBFeypRVa1jJzbDjgrl86QPmBtjU56st36aE

**Comment by 0xd4d** [comment] 2019-09-23 14:02
Attaching a file here is as simple as dragging and dropping the file in the text editor. There's no need for external download sites.

Can you add a small, self contained repro that shows how to reproduce this?

**Comment by CursedSheep** [comment] 2019-09-23 14:55
It is not allowing me to upload executables here.
Also already commented how to reproduce it. 

Steps to reproduce:

Load file I uploaded in zippyshare with dnlib function ModuleDefMD.Load
Loop through every types and method and if method has body, clear all locals. Or just resolve token of the method "0x0600010A".
Save the file.
Check saved file in dnspy and look for the method, and you'll see locals were unmodified.
Other way to reproduce:

Load the file I uploaded on zippyshare and use dnspy
Try modifying any locals or clearing the locals in the method "0x0600010A".
Save file.
Check saved file in dnspy and look for the method, and you'll see locals were unmodified.

**Comment by 0xd4d** [comment] 2019-09-23 15:07
>  Also already commented how to reproduce it.

I asked for a small self contained example because people forget to include all the necessary info. Your repro steps are incomplete, I can't repro it.

**Comment by 0xd4d** [comment] 2019-09-23 15:14
Make sure you open the written file and not some old copy of the file, which of course will show all locals.

**Comment by CursedSheep** [comment] 2019-09-24 08:51
> Make sure you open the written file and not some old copy of the file, which of course will show all locals.

yeah, i obviously know that, but i was talking about methods containing Locals that has a generic type. Specifically talking about method 0x0600010A.
You could just easily use dnspy and modify its Locals or try removing all its locals. then after that, save it. after that, Load the saved file and check the method 0x0600010A.

**Comment by 0xd4d** [comment] 2019-09-24 10:43
This is the dnlib repo, I wrote code using dnlib and followed your steps without success, that's why I asked for a small self contained repro. Can you attach a small self contained repro?

**Comment by CursedSheep** [comment] 2019-09-29 03:33
here you go. the reproduced file. Also i am having trouble in making deobfuscation for type unscrambler. 

I can't seem to save the file when i changed the instruction operand for instructions with opcode (constrained.) and (Box).
![image](https://user-images.githubusercontent.com/44673993/65825686-66e44900-e2ac-11e9-8b04-4b209e88736b.png)

I am getting this error
![image](https://user-images.githubusercontent.com/44673993/65825730-01448c80-e2ad-11e9-9814-e8da008fc90c.png)

**Comment by 0xd4d** [comment] 2019-09-29 06:07
> edit: nvm fixed it.

Great, closing the issue.

**Closed by 0xd4d** 2019-09-29 06:07 UTC
