### ISSUE TITLE
Importer.Import doesn't use MethodDef with ImporterOptions.TryToUseDefs

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#312] opened 2019-10-12 13:37 UTC
```
var importer = new Importer(module, ImporterOptions.TryToUseDefs, new GenericParamContext(), new AssemblyVersionMapper(module));
importer.Import(mi);
```
After a lot of time, I find the reason: TypeDef.FindMethod failed because of PrivateScope.

I find more and more issues about PrivateScope, what's the meaning of PrivateScope? Why do you always check it? It works fine if don't check it.

**Comment by 0xd4d** [comment] 2019-10-12 15:53
Add repo code or it's impossible to help you.

If this is a dupe of your other issue, close this issue.

**Comment by CreateAndInject** [comment] 2019-10-14 08:20
[Test.zip](https://github.com/0xd4d/dnlib/files/3723567/Test.zip)

**Comment by 0xd4d** [comment] 2020-03-19 18:46
> After a lot of time, I find the reason: TypeDef.FindMethod failed because of PrivateScope.

Duplicate of https://github.com/0xd4d/dnlib/issues/253

**Closed by 0xd4d** 2020-03-19 18:46 UTC
