### ISSUE TITLE
Problem with DataReader

### ISSUE THREAD

**Issue by CursedSheep** [0xd4d/dnlib#375] opened 2020-07-01 12:26 UTC
OutOfMemoryException occurs when DataReader is reading a large string repeatedly. 
I am suggesting to make a cache system for strings so that it won't have to read the large string over and over. It'll just check a dictionary if the (offset as key) exists and return the value for the key.

**Comment by 0xd4d** [comment] 2020-07-02 18:16
Is this a dupe of https://github.com/0xd4d/dnlib/issues/361

**Comment by CursedSheep** [comment] 2020-07-03 03:13
Kinda. I thought i closed that issue already. However, This pretty much explains the cause of the problem and explains the possible solution for the issue.

**Comment by wtfsck** [comment] 2021-12-05 18:45
Closing this, I won't add a string cache.

**Closed by wtfsck** 2021-12-05 18:45 UTC
