### ISSUE TITLE
Argument Exception

### ISSUE THREAD

**Issue by anywhereyang** [0xd4d/dnlib#330] opened 2019-12-14 08:42 UTC
a Exception occred when i use DynamicMethodBodyReader to read DynamicMethod, 

i use dnlib to dump the protector dynamic method ,so i dont know the original declaration type
,please help me！

Exception Stack Trace:
at System.Reflection.FieldInfo.GetFieldFromHandle(RuntimeFieldHandle handle)
   at dnlib.DotNet.Emit.DynamicMethodBodyReader.ImportField(UInt32 rid) pos D:\code\diagnostic\dnlib-2.1_VS2010\src\DotNet\Emit\DynamicMethodBodyReader.cs:line 507
   at dnlib.DotNet.Emit.DynamicMethodBodyReader.ReadToken(UInt32 token) pos D:\code\diagnostic\dnlib-2.1_VS2010\src\DotNet\Emit\DynamicMethodBodyReader.cs:line 433
   at dnlib.DotNet.Emit.DynamicMethodBodyReader.ReadInlineField(Instruction instr) pos D:\code\diagnostic\dnlib-2.1_VS2010\src\DotNet\Emit\DynamicMethodBodyReader.cs:line 391
   at dnlib.DotNet.Emit.MethodBodyReaderBase.ReadOperand(Instruction instr) pos D:\code\diagnostic\dnlib-2.1_VS2010\src\DotNet\Emit\MethodBodyReaderBase.cs:line 232
   at dnlib.DotNet.Emit.MethodBodyReaderBase.ReadOneInstruction() pos D:\code\diagnostic\dnlib-2.1_VS2010\src\DotNet\Emit\MethodBodyReaderBase.cs:line 202
   at dnlib.DotNet.Emit.MethodBodyReaderBase.ReadInstructionsNumBytes(UInt32 codeSize) pos D:\code\diagnostic\dnlib-2.1_VS2010\src\DotNet\Emit\MethodBodyReaderBase.cs:line 132
   at dnlib.DotNet.Emit.DynamicMethodBodyReader.Read() pos D:\code\diagnostic\dnlib-2.1_VS2010\src\DotNet\Emit\DynamicMethodBodyReader.cs:line 278
   at dnlib.Examples.Example6.decryptMethodBody() pos D:\code\diagnostic\dnlib-2.1_VS2010\Examples\Example6.cs:line 271

The Exception Message:
The field target cannot be resolved because the declaration type of the field handle system. Runtime. Compilerservices. Callsite ` 1 [t] is generic. Explicitly provide a declaration type to GetFieldFromHandle 

the exception code pos :
https://github.com/0xd4d/dnlib/blob/a0b58a65c8d21ca14c79a8f6bf06b478e324e19c/src/DotNet/Emit/DynamicMethodBodyReader.cs#L456

My Code:
```c#
void decryptMethodBody()
{
	Type decryptClass = ass.GetType("7120480");
	try
	{
		//make dynamicMehtod
		md = (DynamicMethod)decryptClass.InvokeMember("80071137", tmpFlags, null, null, new object[] { null, method, true });
	}
	catch (Exception e)
	{
		Console.WriteLine("decrypt Failed:" + curType.FullName + ":" + curMethod.Name + e.Message);
	}
	
	/// other code ...
	
	DynamicMethodBodyReader reader = new DynamicMethodBodyReader(module, md);
      
        // occur Argument Exception
	if (reader.Read())
	{
		reader.RestoreMethod(curMethod);
	}
	else
	{
		Console.WriteLine("Restore Failed:" + curType.FullName + ":" + curMethod.Name);
	}		
}
```

**Comment by 0xd4d** [comment] 2019-12-21 11:28
Looks like a dupe of https://github.com/0xd4d/dnlib/issues/298

**Comment by anywhereyang** [comment] 2019-12-23 02:03
Yes.

**Comment by 0xd4d** [comment] 2019-12-26 17:43
Duplicate of #298

**Closed by 0xd4d** 2019-12-26 17:43 UTC
